# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C3ATORecordTranslator.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(592, 360)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnSingleFileTrans = QtWidgets.QPushButton(Dialog)
        self.btnSingleFileTrans.setMinimumSize(QtCore.QSize(0, 0))
        self.btnSingleFileTrans.setStyleSheet("background-color: rgb(158, 229, 167);")
        self.btnSingleFileTrans.setDefault(False)
        self.btnSingleFileTrans.setObjectName("btnSingleFileTrans")
        self.horizontalLayout.addWidget(self.btnSingleFileTrans)
        self.btnMultiFileTrans = QtWidgets.QPushButton(Dialog)
        self.btnMultiFileTrans.setStyleSheet("background-color: rgb(255, 255, 222);")
        self.btnMultiFileTrans.setObjectName("btnMultiFileTrans")
        self.horizontalLayout.addWidget(self.btnMultiFileTrans)
        self.btnDirFileTrans = QtWidgets.QPushButton(Dialog)
        self.btnDirFileTrans.setStyleSheet("background-color: rgb(176, 199, 213);")
        self.btnDirFileTrans.setFlat(False)
        self.btnDirFileTrans.setObjectName("btnDirFileTrans")
        self.horizontalLayout.addWidget(self.btnDirFileTrans)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.ledC3ATOPath = QtWidgets.QLineEdit(Dialog)
        self.ledC3ATOPath.setObjectName("ledC3ATOPath")
        self.verticalLayout.addWidget(self.ledC3ATOPath)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.barCurC3ATOProcess = QtWidgets.QProgressBar(Dialog)
        self.barCurC3ATOProcess.setProperty("value", 24)
        self.barCurC3ATOProcess.setObjectName("barCurC3ATOProcess")
        self.verticalLayout.addWidget(self.barCurC3ATOProcess)
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.barAllC3ATOProcess = QtWidgets.QProgressBar(Dialog)
        self.barAllC3ATOProcess.setProperty("value", 24)
        self.barAllC3ATOProcess.setObjectName("barAllC3ATOProcess")
        self.verticalLayout.addWidget(self.barAllC3ATOProcess)
        self.textC3ATOProcess = QtWidgets.QTextEdit(Dialog)
        self.textC3ATOProcess.setObjectName("textC3ATOProcess")
        self.verticalLayout.addWidget(self.textC3ATOProcess)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.btnOK = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnOK.sizePolicy().hasHeightForWidth())
        self.btnOK.setSizePolicy(sizePolicy)
        self.btnOK.setObjectName("btnOK")
        self.horizontalLayout_2.addWidget(self.btnOK)
        self.btnCancel = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnCancel.sizePolicy().hasHeightForWidth())
        self.btnCancel.setSizePolicy(sizePolicy)
        self.btnCancel.setFlat(False)
        self.btnCancel.setObjectName("btnCancel")
        self.horizontalLayout_2.addWidget(self.btnCancel)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.btnSingleFileTrans.setText(_translate("Dialog", "单记录文件转义"))
        self.btnMultiFileTrans.setText(_translate("Dialog", "多记录文件转义"))
        self.btnDirFileTrans.setText(_translate("Dialog", "目录记录文件转义"))
        self.label.setText(_translate("Dialog", "转义文件选择："))
        self.label_2.setText(_translate("Dialog", "当前文件转义进度："))
        self.label_3.setText(_translate("Dialog", "总进度："))
        self.btnOK.setText(_translate("Dialog", "执行"))
        self.btnCancel.setText(_translate("Dialog", "取消"))

