# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LogMainWin.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(889, 559)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setStyleSheet("background-color: rgb(193, 193, 193);")
        self.widget.setObjectName("widget")
        self.verticalLayout_2.addWidget(self.widget)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.CBlevel = QtWidgets.QCheckBox(self.centralwidget)
        self.CBlevel.setMaximumSize(QtCore.QSize(101, 16))
        self.CBlevel.setObjectName("CBlevel")
        self.gridLayout_3.addWidget(self.CBlevel, 1, 3, 1, 1)
        self.CBvato = QtWidgets.QCheckBox(self.centralwidget)
        self.CBvato.setMaximumSize(QtCore.QSize(101, 16))
        self.CBvato.setObjectName("CBvato")
        self.gridLayout_3.addWidget(self.CBvato, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 1, 4, 1, 1)
        self.CBacc = QtWidgets.QCheckBox(self.centralwidget)
        self.CBacc.setMaximumSize(QtCore.QSize(101, 16))
        self.CBacc.setObjectName("CBacc")
        self.gridLayout_3.addWidget(self.CBacc, 0, 5, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 1, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem2, 0, 0, 1, 1)
        self.CBceilv = QtWidgets.QCheckBox(self.centralwidget)
        self.CBceilv.setMaximumSize(QtCore.QSize(101, 16))
        self.CBceilv.setObjectName("CBceilv")
        self.gridLayout_3.addWidget(self.CBceilv, 0, 3, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem3, 0, 6, 1, 1)
        self.CBramp = QtWidgets.QCheckBox(self.centralwidget)
        self.CBramp.setMaximumSize(QtCore.QSize(101, 16))
        self.CBramp.setObjectName("CBramp")
        self.gridLayout_3.addWidget(self.CBramp, 1, 5, 1, 1)
        self.CBcmdv = QtWidgets.QCheckBox(self.centralwidget)
        self.CBcmdv.setMaximumSize(QtCore.QSize(101, 16))
        self.CBcmdv.setObjectName("CBcmdv")
        self.gridLayout_3.addWidget(self.CBcmdv, 1, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_3)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.tableWidget = QtWidgets.QTableWidget(self.splitter)
        self.tableWidget.setMinimumSize(QtCore.QSize(250, 0))
        self.tableWidget.setMaximumSize(QtCore.QSize(280, 3000))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.progressBar = QtWidgets.QProgressBar(self.splitter)
        self.progressBar.setMinimumSize(QtCore.QSize(250, 0))
        self.progressBar.setMaximumSize(QtCore.QSize(280, 30))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.textEdit = QtWidgets.QTextEdit(self.splitter)
        self.textEdit.setMinimumSize(QtCore.QSize(250, 0))
        self.textEdit.setMaximumSize(QtCore.QSize(280, 500))
        self.textEdit.setObjectName("textEdit")
        self.horizontalLayout.addWidget(self.splitter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 889, 23))
        self.menubar.setObjectName("menubar")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(self.menubar)
        self.menu_3.setObjectName("menu_3")
        self.menu_4 = QtWidgets.QMenu(self.menubar)
        self.menu_4.setObjectName("menu_4")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.fileOpen = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("IconFiles/file.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.fileOpen.setIcon(icon)
        self.fileOpen.setObjectName("fileOpen")
        self.fileClose = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("IconFiles/close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.fileClose.setIcon(icon1)
        self.fileClose.setObjectName("fileClose")
        self.fileSave = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("IconFiles/save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.fileSave.setIcon(icon2)
        self.fileSave.setObjectName("fileSave")
        self.Exit = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("IconFiles/quit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Exit.setIcon(icon3)
        self.Exit.setObjectName("Exit")
        self.actionVersion = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("IconFiles/version.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionVersion.setIcon(icon4)
        self.actionVersion.setObjectName("actionVersion")
        self.actionHelp = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("IconFiles/help.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionHelp.setIcon(icon5)
        self.actionHelp.setObjectName("actionHelp")
        self.actionTag = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("IconFiles/Tag.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionTag.setIcon(icon6)
        self.actionTag.setObjectName("actionTag")
        self.actionView = QtWidgets.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("IconFiles/view.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionView.setIcon(icon7)
        self.actionView.setObjectName("actionView")
        self.menu_2.addAction(self.actionTag)
        self.menu_2.addAction(self.actionView)
        self.menu_4.addAction(self.actionHelp)
        self.menu_4.addAction(self.actionVersion)
        self.menu.addAction(self.fileOpen)
        self.menu.addAction(self.fileClose)
        self.menu.addAction(self.fileSave)
        self.menu.addAction(self.Exit)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())
        self.menubar.addAction(self.menu_4.menuAction())
        self.toolBar.addAction(self.actionTag)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionView)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.CBlevel.setText(_translate("MainWindow", "S-LEVEL Curve"))
        self.CBvato.setText(_translate("MainWindow", "S-Vato Curve"))
        self.CBacc.setText(_translate("MainWindow", "S-Acc Curve"))
        self.CBceilv.setText(_translate("MainWindow", "S-Vceil Curve"))
        self.CBramp.setText(_translate("MainWindow", "S-Ramp Curve"))
        self.CBcmdv.setText(_translate("MainWindow", "S-Vcmdv Curve"))
        self.menu_2.setTitle(_translate("MainWindow", "编辑"))
        self.menu_3.setTitle(_translate("MainWindow", "工具"))
        self.menu_4.setTitle(_translate("MainWindow", "关于"))
        self.menu.setTitle(_translate("MainWindow", "文件"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.fileOpen.setText(_translate("MainWindow", "打开"))
        self.fileClose.setText(_translate("MainWindow", "关闭"))
        self.fileSave.setText(_translate("MainWindow", "保存"))
        self.Exit.setText(_translate("MainWindow", "退出"))
        self.actionVersion.setText(_translate("MainWindow", "版本信息"))
        self.actionHelp.setText(_translate("MainWindow", "帮助"))
        self.actionTag.setText(_translate("MainWindow", "标注模式"))
        self.actionView.setText(_translate("MainWindow", "浏览模式"))

