# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LogMainWin.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 597)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.layoutWidget = QtWidgets.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget = QtWidgets.QWidget(self.layoutWidget)
        self.widget.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(7)
        font.setBold(False)
        font.setWeight(50)
        self.widget.setFont(font)
        self.widget.setStyleSheet("background-color: rgb(220, 220, 220);")
        self.widget.setObjectName("widget")
        self.verticalLayout_2.addWidget(self.widget)
        self.verticalLayout_5.addLayout(self.verticalLayout_2)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.CBramp = QtWidgets.QCheckBox(self.layoutWidget)
        self.CBramp.setMaximumSize(QtCore.QSize(101, 16))
        self.CBramp.setObjectName("CBramp")
        self.gridLayout_3.addWidget(self.CBramp, 1, 5, 1, 1)
        self.CBatpcmdv = QtWidgets.QCheckBox(self.layoutWidget)
        self.CBatpcmdv.setMaximumSize(QtCore.QSize(101, 16))
        self.CBatpcmdv.setObjectName("CBatpcmdv")
        self.gridLayout_3.addWidget(self.CBatpcmdv, 0, 3, 1, 1)
        self.CBcmdv = QtWidgets.QCheckBox(self.layoutWidget)
        self.CBcmdv.setMaximumSize(QtCore.QSize(101, 16))
        self.CBcmdv.setObjectName("CBcmdv")
        self.gridLayout_3.addWidget(self.CBcmdv, 1, 1, 1, 1)
        self.CBacc = QtWidgets.QCheckBox(self.layoutWidget)
        self.CBacc.setMaximumSize(QtCore.QSize(101, 16))
        self.CBacc.setObjectName("CBacc")
        self.gridLayout_3.addWidget(self.CBacc, 0, 5, 1, 1)
        self.CBvato = QtWidgets.QCheckBox(self.layoutWidget)
        self.CBvato.setMaximumSize(QtCore.QSize(101, 16))
        self.CBvato.setObjectName("CBvato")
        self.gridLayout_3.addWidget(self.CBvato, 0, 1, 1, 1)
        self.CBlevel = QtWidgets.QCheckBox(self.layoutWidget)
        self.CBlevel.setMaximumSize(QtCore.QSize(101, 16))
        self.CBlevel.setObjectName("CBlevel")
        self.gridLayout_3.addWidget(self.CBlevel, 1, 3, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 1, 4, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 1, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem2, 0, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem3, 0, 6, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout_3)
        self.layoutWidget1 = QtWidgets.QWidget(self.splitter)
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget1)
        self.label.setMinimumSize(QtCore.QSize(50, 0))
        self.label.setMaximumSize(QtCore.QSize(50, 16777215))
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_2.setMinimumSize(QtCore.QSize(90, 0))
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_3.setMaximumSize(QtCore.QSize(55, 16777215))
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.spinBox = QtWidgets.QSpinBox(self.layoutWidget1)
        self.spinBox.setMaximumSize(QtCore.QSize(70, 16777215))
        self.spinBox.setObjectName("spinBox")
        self.horizontalLayout.addWidget(self.spinBox)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tabWidget = QtWidgets.QTabWidget(self.layoutWidget1)
        self.tabWidget.setMaximumSize(QtCore.QSize(800, 16777215))
        self.tabWidget.setStyleSheet("")
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setObjectName("tabWidget")
        self.atotab = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(30)
        sizePolicy.setHeightForWidth(self.atotab.sizePolicy().hasHeightForWidth())
        self.atotab.setSizePolicy(sizePolicy)
        self.atotab.setMaximumSize(QtCore.QSize(800, 16777215))
        self.atotab.setAutoFillBackground(False)
        self.atotab.setObjectName("atotab")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.atotab)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.splitter_2 = QtWidgets.QSplitter(self.atotab)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName("splitter_2")
        self.tableWidget = QtWidgets.QTableWidget(self.splitter_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        self.tableWidget.setMaximumSize(QtCore.QSize(800, 16777215))
        self.tableWidget.setStyleSheet("background-color: rgb(224, 238, 224);")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.treeWidget = QtWidgets.QTreeWidget(self.splitter_2)
        self.treeWidget.setMaximumSize(QtCore.QSize(800, 16777215))
        self.treeWidget.setStyleSheet("background-color: rgb(230, 230, 255);")
        self.treeWidget.setObjectName("treeWidget")
        self.treeWidget.headerItem().setText(0, "1")
        self.treeWidget.header().setDefaultSectionSize(80)
        self.horizontalLayout_2.addWidget(self.splitter_2)
        self.tabWidget.addTab(self.atotab, "")
        self.fietab = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fietab.sizePolicy().hasHeightForWidth())
        self.fietab.setSizePolicy(sizePolicy)
        self.fietab.setMaximumSize(QtCore.QSize(800, 16777215))
        self.fietab.setObjectName("fietab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.fietab)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.treeView = QtWidgets.QTreeView(self.fietab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(30)
        sizePolicy.setHeightForWidth(self.treeView.sizePolicy().hasHeightForWidth())
        self.treeView.setSizePolicy(sizePolicy)
        self.treeView.setMaximumSize(QtCore.QSize(800, 16777215))
        self.treeView.setObjectName("treeView")
        self.verticalLayout_3.addWidget(self.treeView)
        self.tabWidget.addTab(self.fietab, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.progressBar = QtWidgets.QProgressBar(self.layoutWidget1)
        self.progressBar.setMinimumSize(QtCore.QSize(250, 0))
        self.progressBar.setMaximumSize(QtCore.QSize(800, 30))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout.addWidget(self.progressBar)
        self.textEdit = QtWidgets.QTextEdit(self.layoutWidget1)
        self.textEdit.setMinimumSize(QtCore.QSize(250, 0))
        self.textEdit.setMaximumSize(QtCore.QSize(800, 100))
        self.textEdit.setStyleSheet("background-color: rgb(255, 250, 205);")
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout.addWidget(self.textEdit)
        self.horizontalLayout_3.addWidget(self.splitter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 23))
        self.menubar.setObjectName("menubar")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(self.menubar)
        self.menu_3.setObjectName("menu_3")
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setObjectName("action")
        self.menu_4 = QtWidgets.QMenu(self.menubar)
        self.menu_4.setObjectName("menu_4")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.fileOpen = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("IconFiles/file.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.fileOpen.setIcon(icon)
        self.fileOpen.setObjectName("fileOpen")
        self.fileClose = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("IconFiles/close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.fileClose.setIcon(icon1)
        self.fileClose.setObjectName("fileClose")
        self.fileSave = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("IconFiles/save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.fileSave.setIcon(icon2)
        self.fileSave.setObjectName("fileSave")
        self.Exit = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("IconFiles/quit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Exit.setIcon(icon3)
        self.Exit.setObjectName("Exit")
        self.actionVersion = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("IconFiles/version.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionVersion.setIcon(icon4)
        self.actionVersion.setObjectName("actionVersion")
        self.actionHelp = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("IconFiles/help.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionHelp.setIcon(icon5)
        self.actionHelp.setObjectName("actionHelp")
        self.actionTag = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("IconFiles/tag.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionTag.setIcon(icon6)
        self.actionTag.setObjectName("actionTag")
        self.actionView = QtWidgets.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("IconFiles/view.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionView.setIcon(icon7)
        self.actionView.setObjectName("actionView")
        self.actionPan = QtWidgets.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("IconFiles/pan.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPan.setIcon(icon8)
        self.actionPan.setObjectName("actionPan")
        self.actionZoom = QtWidgets.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("IconFiles/zoom.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionZoom.setIcon(icon9)
        self.actionZoom.setObjectName("actionZoom")
        self.actionConfig = QtWidgets.QAction(MainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("IconFiles/config.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionConfig.setIcon(icon10)
        self.actionConfig.setObjectName("actionConfig")
        self.actionFwd = QtWidgets.QAction(MainWindow)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("IconFiles/forward.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFwd.setIcon(icon11)
        self.actionFwd.setObjectName("actionFwd")
        self.actionBck = QtWidgets.QAction(MainWindow)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap("IconFiles/back.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionBck.setIcon(icon12)
        self.actionBck.setObjectName("actionBck")
        self.actionEdit = QtWidgets.QAction(MainWindow)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap("IconFiles/edit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionEdit.setIcon(icon13)
        self.actionEdit.setObjectName("actionEdit")
        self.actionReset = QtWidgets.QAction(MainWindow)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap("IconFiles/reset.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionReset.setIcon(icon14)
        self.actionReset.setObjectName("actionReset")
        self.actionHome = QtWidgets.QAction(MainWindow)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap("IconFiles/home.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionHome.setIcon(icon15)
        self.actionHome.setObjectName("actionHome")
        self.actionPrint = QtWidgets.QAction(MainWindow)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap("IconFiles/print.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon16.addPixmap(QtGui.QPixmap("../../.designer/backup/IconFiles/print.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionPrint.setIcon(icon16)
        self.actionPrint.setObjectName("actionPrint")
        self.actionVS = QtWidgets.QAction(MainWindow)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap("IconFiles/vscurve.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionVS.setIcon(icon17)
        self.actionVS.setObjectName("actionVS")
        self.actionCS = QtWidgets.QAction(MainWindow)
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap("IconFiles/cyclecurve.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCS.setIcon(icon18)
        self.actionCS.setObjectName("actionCS")
        self.menu_2.addAction(self.actionTag)
        self.menu_2.addAction(self.actionView)
        self.menu_2.addAction(self.actionVS)
        self.menu_2.addAction(self.actionCS)
        self.menu_3.addAction(self.actionPan)
        self.menu_3.addAction(self.actionZoom)
        self.menu_3.addAction(self.actionEdit)
        self.menu_3.addAction(self.actionConfig)
        self.menu_3.addAction(self.actionReset)
        self.menu_3.addAction(self.actionFwd)
        self.menu_3.addAction(self.actionBck)
        self.menu_3.addAction(self.actionHome)
        self.menu_4.addAction(self.actionHelp)
        self.menu_4.addAction(self.actionVersion)
        self.menu.addAction(self.fileOpen)
        self.menu.addAction(self.fileClose)
        self.menu.addAction(self.fileSave)
        self.menu.addAction(self.Exit)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())
        self.menubar.addAction(self.menu_4.menuAction())
        self.toolBar.addAction(self.actionTag)
        self.toolBar.addAction(self.actionView)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionHome)
        self.toolBar.addAction(self.actionBck)
        self.toolBar.addAction(self.actionFwd)
        self.toolBar.addAction(self.actionEdit)
        self.toolBar.addAction(self.actionConfig)
        self.toolBar.addAction(self.actionZoom)
        self.toolBar.addAction(self.actionPan)
        self.toolBar.addAction(self.actionReset)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionPrint)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.CBramp.setText(_translate("MainWindow", "S-Ramp"))
        self.CBatpcmdv.setText(_translate("MainWindow", "S-Vatpcmdv"))
        self.CBcmdv.setText(_translate("MainWindow", "S-Vatocmdv"))
        self.CBacc.setText(_translate("MainWindow", "S-Acc"))
        self.CBvato.setText(_translate("MainWindow", "S-Vato"))
        self.CBlevel.setText(_translate("MainWindow", "S-Level"))
        self.label.setText(_translate("MainWindow", "TextLabel"))
        self.label_2.setText(_translate("MainWindow", "TextLabel"))
        self.label_3.setText(_translate("MainWindow", "TextLabel"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.atotab), _translate("MainWindow", "ATO控制信息"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.fietab), _translate("MainWindow", "文件选择框"))
        self.menu_2.setTitle(_translate("MainWindow", "编辑"))
        self.menu_3.setTitle(_translate("MainWindow", "工具"))
        self.menu_4.setTitle(_translate("MainWindow", "关于"))
        self.menu.setTitle(_translate("MainWindow", "文件"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.fileOpen.setText(_translate("MainWindow", "打开"))
        self.fileClose.setText(_translate("MainWindow", "关闭"))
        self.fileSave.setText(_translate("MainWindow", "保存"))
        self.Exit.setText(_translate("MainWindow", "退出"))
        self.actionVersion.setText(_translate("MainWindow", "版本信息"))
        self.actionHelp.setText(_translate("MainWindow", "帮助"))
        self.actionTag.setText(_translate("MainWindow", "标注模式"))
        self.actionView.setText(_translate("MainWindow", "浏览模式"))
        self.actionPan.setText(_translate("MainWindow", "图形拖放"))
        self.actionPan.setToolTip(_translate("MainWindow", "图形拖放，左键拖动，右键坐标轴缩放"))
        self.actionZoom.setText(_translate("MainWindow", "图形缩放"))
        self.actionZoom.setToolTip(_translate("MainWindow", "图形缩放，鼠标拖拽放大"))
        self.actionConfig.setText(_translate("MainWindow", "参数配置"))
        self.actionFwd.setText(_translate("MainWindow", "前进"))
        self.actionBck.setText(_translate("MainWindow", "后退"))
        self.actionEdit.setText(_translate("MainWindow", "图形编辑"))
        self.actionReset.setText(_translate("MainWindow", "重置图形"))
        self.actionReset.setToolTip(_translate("MainWindow", "重新绘制曲线"))
        self.actionHome.setText(_translate("MainWindow", "原始显示"))
        self.actionHome.setToolTip(_translate("MainWindow", "显示初始坐标轴"))
        self.actionPrint.setText(_translate("MainWindow", "打印周期"))
        self.actionPrint.setToolTip(_translate("MainWindow", "打印当前周期记录"))
        self.actionVS.setText(_translate("MainWindow", "位置速度曲线"))
        self.actionCS.setText(_translate("MainWindow", "周期速度曲线"))

import IconFiles_rc
