# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LogMainWin.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 603)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.splitter_3 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_3.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_3.setObjectName("splitter_3")
        self.splitter = QtWidgets.QSplitter(self.splitter_3)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.stackedWidget = QtWidgets.QStackedWidget(self.splitter)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.page_3)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.widget = QtWidgets.QWidget(self.page_3)
        self.widget.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(7)
        font.setBold(False)
        font.setWeight(50)
        self.widget.setFont(font)
        self.widget.setStyleSheet("background-color: rgb(220, 220, 220);")
        self.widget.setObjectName("widget")
        self.verticalLayout_5.addWidget(self.widget)
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.page_4)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.splitter_4 = QtWidgets.QSplitter(self.page_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter_4.sizePolicy().hasHeightForWidth())
        self.splitter_4.setSizePolicy(sizePolicy)
        self.splitter_4.setOrientation(QtCore.Qt.Vertical)
        self.splitter_4.setHandleWidth(5)
        self.splitter_4.setObjectName("splitter_4")
        self.layoutWidget = QtWidgets.QWidget(self.splitter_4)
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_7.addWidget(self.label_4)
        self.lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_7.addWidget(self.lineEdit)
        self.btn_SavePath = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_SavePath.setMaximumSize(QtCore.QSize(24, 16777215))
        self.btn_SavePath.setAutoDefault(True)
        self.btn_SavePath.setObjectName("btn_SavePath")
        self.horizontalLayout_7.addWidget(self.btn_SavePath)
        self.comboBox = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox.setObjectName("comboBox")
        self.horizontalLayout_7.addWidget(self.comboBox, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.btn_PortLink = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_PortLink.setStyleSheet("background-color: rgb(238, 86, 63);")
        self.btn_PortLink.setAutoDefault(True)
        self.btn_PortLink.setDefault(False)
        self.btn_PortLink.setFlat(False)
        self.btn_PortLink.setObjectName("btn_PortLink")
        self.horizontalLayout_7.addWidget(self.btn_PortLink)
        self.layoutWidget1 = QtWidgets.QWidget(self.splitter_4)
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.gp_ato2tcms = QtWidgets.QGroupBox(self.layoutWidget1)
        self.gp_ato2tcms.setObjectName("gp_ato2tcms")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.gp_ato2tcms)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.gp_ato2tcms_ctrl = QtWidgets.QGroupBox(self.gp_ato2tcms)
        self.gp_ato2tcms_ctrl.setObjectName("gp_ato2tcms_ctrl")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gp_ato2tcms_ctrl)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.led_ctrl_tract = QtWidgets.QLineEdit(self.gp_ato2tcms_ctrl)
        self.led_ctrl_tract.setObjectName("led_ctrl_tract")
        self.gridLayout_4.addWidget(self.led_ctrl_tract, 0, 5, 1, 1)
        self.led_ctrl_brake = QtWidgets.QLineEdit(self.gp_ato2tcms_ctrl)
        self.led_ctrl_brake.setObjectName("led_ctrl_brake")
        self.gridLayout_4.addWidget(self.led_ctrl_brake, 1, 5, 1, 1)
        self.lbl_ctrl_hrt = QtWidgets.QLabel(self.gp_ato2tcms_ctrl)
        self.lbl_ctrl_hrt.setObjectName("lbl_ctrl_hrt")
        self.gridLayout_4.addWidget(self.lbl_ctrl_hrt, 0, 0, 1, 1)
        self.led_ctrl_atovalid = QtWidgets.QLineEdit(self.gp_ato2tcms_ctrl)
        self.led_ctrl_atovalid.setObjectName("led_ctrl_atovalid")
        self.gridLayout_4.addWidget(self.led_ctrl_atovalid, 0, 3, 1, 1)
        self.lbl_ctrl_costspeed = QtWidgets.QLabel(self.gp_ato2tcms_ctrl)
        self.lbl_ctrl_costspeed.setObjectName("lbl_ctrl_costspeed")
        self.gridLayout_4.addWidget(self.lbl_ctrl_costspeed, 2, 4, 1, 1)
        self.lbl_ctrl_rdoor = QtWidgets.QLabel(self.gp_ato2tcms_ctrl)
        self.lbl_ctrl_rdoor.setObjectName("lbl_ctrl_rdoor")
        self.gridLayout_4.addWidget(self.lbl_ctrl_rdoor, 2, 2, 1, 1)
        self.led_ctrl_ldoor = QtWidgets.QLineEdit(self.gp_ato2tcms_ctrl)
        self.led_ctrl_ldoor.setObjectName("led_ctrl_ldoor")
        self.gridLayout_4.addWidget(self.led_ctrl_ldoor, 2, 1, 1, 1)
        self.led_ctrl_rdoor = QtWidgets.QLineEdit(self.gp_ato2tcms_ctrl)
        self.led_ctrl_rdoor.setObjectName("led_ctrl_rdoor")
        self.gridLayout_4.addWidget(self.led_ctrl_rdoor, 2, 3, 1, 1)
        self.lbl_ctrl_trac = QtWidgets.QLabel(self.gp_ato2tcms_ctrl)
        self.lbl_ctrl_trac.setObjectName("lbl_ctrl_trac")
        self.gridLayout_4.addWidget(self.lbl_ctrl_trac, 0, 4, 1, 1)
        self.led_ctrl_hrt = QtWidgets.QLineEdit(self.gp_ato2tcms_ctrl)
        self.led_ctrl_hrt.setObjectName("led_ctrl_hrt")
        self.gridLayout_4.addWidget(self.led_ctrl_hrt, 0, 1, 1, 1)
        self.led_ctrl_costspeed = QtWidgets.QLineEdit(self.gp_ato2tcms_ctrl)
        self.led_ctrl_costspeed.setObjectName("led_ctrl_costspeed")
        self.gridLayout_4.addWidget(self.led_ctrl_costspeed, 2, 5, 1, 1)
        self.led_ctrl_tbstat = QtWidgets.QLineEdit(self.gp_ato2tcms_ctrl)
        self.led_ctrl_tbstat.setObjectName("led_ctrl_tbstat")
        self.gridLayout_4.addWidget(self.led_ctrl_tbstat, 1, 1, 1, 1)
        self.lbl_ctrl_brake = QtWidgets.QLabel(self.gp_ato2tcms_ctrl)
        self.lbl_ctrl_brake.setObjectName("lbl_ctrl_brake")
        self.gridLayout_4.addWidget(self.lbl_ctrl_brake, 1, 4, 1, 1)
        self.lbl_ctrl_tbstat = QtWidgets.QLabel(self.gp_ato2tcms_ctrl)
        self.lbl_ctrl_tbstat.setObjectName("lbl_ctrl_tbstat")
        self.gridLayout_4.addWidget(self.lbl_ctrl_tbstat, 1, 0, 1, 1)
        self.lbl_ctrl_keepbrake = QtWidgets.QLabel(self.gp_ato2tcms_ctrl)
        self.lbl_ctrl_keepbrake.setObjectName("lbl_ctrl_keepbrake")
        self.gridLayout_4.addWidget(self.lbl_ctrl_keepbrake, 1, 2, 1, 1)
        self.led_ctrl_keepbrake = QtWidgets.QLineEdit(self.gp_ato2tcms_ctrl)
        self.led_ctrl_keepbrake.setObjectName("led_ctrl_keepbrake")
        self.gridLayout_4.addWidget(self.led_ctrl_keepbrake, 1, 3, 1, 1)
        self.lbl_ctrl_ldoor = QtWidgets.QLabel(self.gp_ato2tcms_ctrl)
        self.lbl_ctrl_ldoor.setObjectName("lbl_ctrl_ldoor")
        self.gridLayout_4.addWidget(self.lbl_ctrl_ldoor, 2, 0, 1, 1)
        self.lbl_ctrl_atovalid = QtWidgets.QLabel(self.gp_ato2tcms_ctrl)
        self.lbl_ctrl_atovalid.setObjectName("lbl_ctrl_atovalid")
        self.gridLayout_4.addWidget(self.lbl_ctrl_atovalid, 0, 2, 1, 1)
        self.lbl_startlamp = QtWidgets.QLabel(self.gp_ato2tcms_ctrl)
        self.lbl_startlamp.setObjectName("lbl_startlamp")
        self.gridLayout_4.addWidget(self.lbl_startlamp, 3, 0, 1, 1)
        self.led_ctrl_starlamp = QtWidgets.QLineEdit(self.gp_ato2tcms_ctrl)
        self.led_ctrl_starlamp.setObjectName("led_ctrl_starlamp")
        self.gridLayout_4.addWidget(self.led_ctrl_starlamp, 3, 1, 1, 1)
        self.lbl_ctrl_aimspeed = QtWidgets.QLabel(self.gp_ato2tcms_ctrl)
        self.lbl_ctrl_aimspeed.setObjectName("lbl_ctrl_aimspeed")
        self.gridLayout_4.addWidget(self.lbl_ctrl_aimspeed, 3, 2, 1, 1)
        self.led_ctrl_aimspeed = QtWidgets.QLineEdit(self.gp_ato2tcms_ctrl)
        self.led_ctrl_aimspeed.setObjectName("led_ctrl_aimspeed")
        self.gridLayout_4.addWidget(self.led_ctrl_aimspeed, 3, 3, 1, 1)
        self.verticalLayout_7.addWidget(self.gp_ato2tcms_ctrl)
        self.gp_ato2tcms_status = QtWidgets.QGroupBox(self.gp_ato2tcms)
        self.gp_ato2tcms_status.setObjectName("gp_ato2tcms_status")
        self.gridLayout = QtWidgets.QGridLayout(self.gp_ato2tcms_status)
        self.gridLayout.setObjectName("gridLayout")
        self.led_stat_tunnelin = QtWidgets.QLineEdit(self.gp_ato2tcms_status)
        self.led_stat_tunnelin.setObjectName("led_stat_tunnelin")
        self.gridLayout.addWidget(self.led_stat_tunnelin, 0, 7, 1, 1)
        self.lbl_stat_tunnelin = QtWidgets.QLabel(self.gp_ato2tcms_status)
        self.lbl_stat_tunnelin.setObjectName("lbl_stat_tunnelin")
        self.gridLayout.addWidget(self.lbl_stat_tunnelin, 0, 6, 1, 1)
        self.lbl_stat_hrt = QtWidgets.QLabel(self.gp_ato2tcms_status)
        self.lbl_stat_hrt.setObjectName("lbl_stat_hrt")
        self.gridLayout.addWidget(self.lbl_stat_hrt, 0, 0, 1, 1)
        self.led_stat_hrt = QtWidgets.QLineEdit(self.gp_ato2tcms_status)
        self.led_stat_hrt.setObjectName("led_stat_hrt")
        self.gridLayout.addWidget(self.led_stat_hrt, 0, 1, 1, 1)
        self.lbl_stat_atospeed = QtWidgets.QLabel(self.gp_ato2tcms_status)
        self.lbl_stat_atospeed.setObjectName("lbl_stat_atospeed")
        self.gridLayout.addWidget(self.lbl_stat_atospeed, 1, 0, 1, 1)
        self.led_stat_atospeed = QtWidgets.QLineEdit(self.gp_ato2tcms_status)
        self.led_stat_atospeed.setObjectName("led_stat_atospeed")
        self.gridLayout.addWidget(self.led_stat_atospeed, 1, 1, 1, 1)
        self.lbl_stat_error = QtWidgets.QLabel(self.gp_ato2tcms_status)
        self.lbl_stat_error.setObjectName("lbl_stat_error")
        self.gridLayout.addWidget(self.lbl_stat_error, 1, 2, 1, 1)
        self.led_stat_error = QtWidgets.QLineEdit(self.gp_ato2tcms_status)
        self.led_stat_error.setObjectName("led_stat_error")
        self.gridLayout.addWidget(self.led_stat_error, 1, 3, 1, 1)
        self.lbl_stat_stonemile = QtWidgets.QLabel(self.gp_ato2tcms_status)
        self.lbl_stat_stonemile.setObjectName("lbl_stat_stonemile")
        self.gridLayout.addWidget(self.lbl_stat_stonemile, 0, 2, 1, 1)
        self.led_stat_stonemile = QtWidgets.QLineEdit(self.gp_ato2tcms_status)
        self.led_stat_stonemile.setObjectName("led_stat_stonemile")
        self.gridLayout.addWidget(self.led_stat_stonemile, 0, 3, 1, 1)
        self.lbl_stat_tunnellen = QtWidgets.QLabel(self.gp_ato2tcms_status)
        self.lbl_stat_tunnellen.setObjectName("lbl_stat_tunnellen")
        self.gridLayout.addWidget(self.lbl_stat_tunnellen, 1, 6, 1, 1)
        self.led_stat_tunnellen = QtWidgets.QLineEdit(self.gp_ato2tcms_status)
        self.led_stat_tunnellen.setObjectName("led_stat_tunnellen")
        self.gridLayout.addWidget(self.led_stat_tunnellen, 1, 7, 1, 1)
        self.verticalLayout_7.addWidget(self.gp_ato2tcms_status)
        self.verticalLayout_6.addLayout(self.verticalLayout_7)
        self.horizontalLayout_4.addWidget(self.gp_ato2tcms)
        self.groupBox_2 = QtWidgets.QGroupBox(self.layoutWidget1)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.lbl_tcms_pm = QtWidgets.QLabel(self.groupBox_2)
        self.lbl_tcms_pm.setObjectName("lbl_tcms_pm")
        self.gridLayout_5.addWidget(self.lbl_tcms_pm, 5, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.lbl_tcms_breakstat = QtWidgets.QLabel(self.groupBox_2)
        self.lbl_tcms_breakstat.setObjectName("lbl_tcms_breakstat")
        self.gridLayout_5.addWidget(self.lbl_tcms_breakstat, 5, 4, 1, 1, QtCore.Qt.AlignHCenter)
        self.lbl_tcms_tbstat = QtWidgets.QLabel(self.groupBox_2)
        self.lbl_tcms_tbstat.setObjectName("lbl_tcms_tbstat")
        self.gridLayout_5.addWidget(self.lbl_tcms_tbstat, 1, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.led_tcms_fbk = QtWidgets.QLineEdit(self.groupBox_2)
        self.led_tcms_fbk.setObjectName("led_tcms_fbk")
        self.gridLayout_5.addWidget(self.led_tcms_fbk, 1, 3, 1, 1)
        self.lbl_tcms_nunits = QtWidgets.QLabel(self.groupBox_2)
        self.lbl_tcms_nunits.setObjectName("lbl_tcms_nunits")
        self.gridLayout_5.addWidget(self.lbl_tcms_nunits, 4, 4, 1, 1, QtCore.Qt.AlignHCenter)
        self.lbl_tcms_am = QtWidgets.QLabel(self.groupBox_2)
        self.lbl_tcms_am.setObjectName("lbl_tcms_am")
        self.gridLayout_5.addWidget(self.lbl_tcms_am, 0, 4, 1, 1, QtCore.Qt.AlignHCenter)
        self.lbl_tcms_hrt = QtWidgets.QLabel(self.groupBox_2)
        self.lbl_tcms_hrt.setObjectName("lbl_tcms_hrt")
        self.gridLayout_5.addWidget(self.lbl_tcms_hrt, 0, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.lbl_tcms_costspeedfbk = QtWidgets.QLabel(self.groupBox_2)
        self.lbl_tcms_costspeedfbk.setObjectName("lbl_tcms_costspeedfbk")
        self.gridLayout_5.addWidget(self.lbl_tcms_costspeedfbk, 3, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.led_tcms_doorstat = QtWidgets.QLineEdit(self.groupBox_2)
        self.led_tcms_doorstat.setObjectName("led_tcms_doorstat")
        self.gridLayout_5.addWidget(self.led_tcms_doorstat, 3, 5, 1, 1)
        self.led_tcms_am = QtWidgets.QLineEdit(self.groupBox_2)
        self.led_tcms_am.setObjectName("led_tcms_am")
        self.gridLayout_5.addWidget(self.led_tcms_am, 0, 5, 1, 1)
        self.led_tcms_nunits = QtWidgets.QLineEdit(self.groupBox_2)
        self.led_tcms_nunits.setObjectName("led_tcms_nunits")
        self.gridLayout_5.addWidget(self.led_tcms_nunits, 4, 5, 1, 1)
        self.led_tcms_dh = QtWidgets.QLineEdit(self.groupBox_2)
        self.led_tcms_dh.setObjectName("led_tcms_dh")
        self.gridLayout_5.addWidget(self.led_tcms_dh, 4, 3, 1, 1)
        self.led_tcms_hrt = QtWidgets.QLineEdit(self.groupBox_2)
        self.led_tcms_hrt.setObjectName("led_tcms_hrt")
        self.gridLayout_5.addWidget(self.led_tcms_hrt, 0, 1, 1, 1)
        self.lbl_tcms_bstat = QtWidgets.QLabel(self.groupBox_2)
        self.lbl_tcms_bstat.setObjectName("lbl_tcms_bstat")
        self.gridLayout_5.addWidget(self.lbl_tcms_bstat, 2, 4, 1, 1)
        self.lbl_tcms_tractfbk = QtWidgets.QLabel(self.groupBox_2)
        self.lbl_tcms_tractfbk.setObjectName("lbl_tcms_tractfbk")
        self.gridLayout_5.addWidget(self.lbl_tcms_tractfbk, 1, 4, 1, 1, QtCore.Qt.AlignHCenter)
        self.led_tcms_mm = QtWidgets.QLineEdit(self.groupBox_2)
        self.led_tcms_mm.setObjectName("led_tcms_mm")
        self.gridLayout_5.addWidget(self.led_tcms_mm, 0, 3, 1, 1)
        self.led_tcms_tractfbk = QtWidgets.QLineEdit(self.groupBox_2)
        self.led_tcms_tractfbk.setObjectName("led_tcms_tractfbk")
        self.gridLayout_5.addWidget(self.led_tcms_tractfbk, 1, 5, 1, 1)
        self.lbl_tcms_mm = QtWidgets.QLabel(self.groupBox_2)
        self.lbl_tcms_mm.setObjectName("lbl_tcms_mm")
        self.gridLayout_5.addWidget(self.lbl_tcms_mm, 0, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.lbl_tcms_doorstat = QtWidgets.QLabel(self.groupBox_2)
        self.lbl_tcms_doorstat.setObjectName("lbl_tcms_doorstat")
        self.gridLayout_5.addWidget(self.lbl_tcms_doorstat, 3, 4, 1, 1)
        self.led_tcms_costspeedfbk = QtWidgets.QLineEdit(self.groupBox_2)
        self.led_tcms_costspeedfbk.setObjectName("led_tcms_costspeedfbk")
        self.gridLayout_5.addWidget(self.led_tcms_costspeedfbk, 3, 3, 1, 1)
        self.lbl_tcms_keepbfbk = QtWidgets.QLabel(self.groupBox_2)
        self.lbl_tcms_keepbfbk.setObjectName("lbl_tcms_keepbfbk")
        self.gridLayout_5.addWidget(self.lbl_tcms_keepbfbk, 2, 2, 1, 1)
        self.led_tcms_pm = QtWidgets.QLineEdit(self.groupBox_2)
        self.led_tcms_pm.setObjectName("led_tcms_pm")
        self.gridLayout_5.addWidget(self.led_tcms_pm, 5, 3, 1, 1)
        self.led_tcms_breakstat = QtWidgets.QLineEdit(self.groupBox_2)
        self.led_tcms_breakstat.setObjectName("led_tcms_breakstat")
        self.gridLayout_5.addWidget(self.led_tcms_breakstat, 5, 5, 1, 1)
        self.lbl_tcms_dh = QtWidgets.QLabel(self.groupBox_2)
        self.lbl_tcms_dh.setObjectName("lbl_tcms_dh")
        self.gridLayout_5.addWidget(self.lbl_tcms_dh, 4, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.led_tcms_bfbk = QtWidgets.QLineEdit(self.groupBox_2)
        self.led_tcms_bfbk.setObjectName("led_tcms_bfbk")
        self.gridLayout_5.addWidget(self.led_tcms_bfbk, 2, 5, 1, 1)
        self.led_tcms_keepbfbk = QtWidgets.QLineEdit(self.groupBox_2)
        self.led_tcms_keepbfbk.setObjectName("led_tcms_keepbfbk")
        self.gridLayout_5.addWidget(self.led_tcms_keepbfbk, 2, 3, 1, 1)
        self.led_tcms_mandoorpm = QtWidgets.QLineEdit(self.groupBox_2)
        self.led_tcms_mandoorpm.setObjectName("led_tcms_mandoorpm")
        self.gridLayout_5.addWidget(self.led_tcms_mandoorpm, 6, 5, 1, 1)
        self.lbl_tcms_mandoorpm = QtWidgets.QLabel(self.groupBox_2)
        self.lbl_tcms_mandoorpm.setObjectName("lbl_tcms_mandoorpm")
        self.gridLayout_5.addWidget(self.lbl_tcms_mandoorpm, 6, 4, 1, 1)
        self.led_tcms_atpdoorpm = QtWidgets.QLineEdit(self.groupBox_2)
        self.led_tcms_atpdoorpm.setObjectName("led_tcms_atpdoorpm")
        self.gridLayout_5.addWidget(self.led_tcms_atpdoorpm, 6, 3, 1, 1)
        self.lbl_tcms_atpdoorpm = QtWidgets.QLabel(self.groupBox_2)
        self.lbl_tcms_atpdoorpm.setObjectName("lbl_tcms_atpdoorpm")
        self.gridLayout_5.addWidget(self.lbl_tcms_atpdoorpm, 6, 2, 1, 1)
        self.led_tcms_weight = QtWidgets.QLineEdit(self.groupBox_2)
        self.led_tcms_weight.setObjectName("led_tcms_weight")
        self.gridLayout_5.addWidget(self.led_tcms_weight, 6, 1, 1, 1)
        self.lbl_tcms_weight = QtWidgets.QLabel(self.groupBox_2)
        self.lbl_tcms_weight.setObjectName("lbl_tcms_weight")
        self.gridLayout_5.addWidget(self.lbl_tcms_weight, 6, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.lbl_tcms_kz = QtWidgets.QLabel(self.groupBox_2)
        self.lbl_tcms_kz.setObjectName("lbl_tcms_kz")
        self.gridLayout_5.addWidget(self.lbl_tcms_kz, 5, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.led_tcms_kz = QtWidgets.QLineEdit(self.groupBox_2)
        self.led_tcms_kz.setObjectName("led_tcms_kz")
        self.gridLayout_5.addWidget(self.led_tcms_kz, 5, 1, 1, 1)
        self.lbl_tcms_rdoorfbk = QtWidgets.QLabel(self.groupBox_2)
        self.lbl_tcms_rdoorfbk.setObjectName("lbl_tcms_rdoorfbk")
        self.gridLayout_5.addWidget(self.lbl_tcms_rdoorfbk, 4, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.led_tcms_rdoorfbk = QtWidgets.QLineEdit(self.groupBox_2)
        self.led_tcms_rdoorfbk.setObjectName("led_tcms_rdoorfbk")
        self.gridLayout_5.addWidget(self.led_tcms_rdoorfbk, 4, 1, 1, 1)
        self.lbl_tcms_ldoorfbk = QtWidgets.QLabel(self.groupBox_2)
        self.lbl_tcms_ldoorfbk.setObjectName("lbl_tcms_ldoorfbk")
        self.gridLayout_5.addWidget(self.lbl_tcms_ldoorfbk, 3, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.led_tcms_ldoorfbk = QtWidgets.QLineEdit(self.groupBox_2)
        self.led_tcms_ldoorfbk.setObjectName("led_tcms_ldoorfbk")
        self.gridLayout_5.addWidget(self.led_tcms_ldoorfbk, 3, 1, 1, 1)
        self.lbl_tcms_atovalid_fbk = QtWidgets.QLabel(self.groupBox_2)
        self.lbl_tcms_atovalid_fbk.setObjectName("lbl_tcms_atovalid_fbk")
        self.gridLayout_5.addWidget(self.lbl_tcms_atovalid_fbk, 2, 0, 1, 1)
        self.led_tcms_atovalid_fbk = QtWidgets.QLineEdit(self.groupBox_2)
        self.led_tcms_atovalid_fbk.setObjectName("led_tcms_atovalid_fbk")
        self.gridLayout_5.addWidget(self.led_tcms_atovalid_fbk, 2, 1, 1, 1)
        self.lbl_tcms_startlampfbk = QtWidgets.QLabel(self.groupBox_2)
        self.lbl_tcms_startlampfbk.setObjectName("lbl_tcms_startlampfbk")
        self.gridLayout_5.addWidget(self.lbl_tcms_startlampfbk, 1, 0, 1, 1)
        self.led_tcms_startlampfbk = QtWidgets.QLineEdit(self.groupBox_2)
        self.led_tcms_startlampfbk.setObjectName("led_tcms_startlampfbk")
        self.gridLayout_5.addWidget(self.led_tcms_startlampfbk, 1, 1, 1, 1)
        self.horizontalLayout_4.addWidget(self.groupBox_2)
        self.layoutWidget2 = QtWidgets.QWidget(self.splitter_4)
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.groupBox_3 = QtWidgets.QGroupBox(self.layoutWidget2)
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.groupBox_6 = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox_6.setObjectName("groupBox_6")
        self.horizontalLayout_8.addWidget(self.groupBox_6)
        self.tableWidgetATPATO = QtWidgets.QTableWidget(self.groupBox_3)
        self.tableWidgetATPATO.setObjectName("tableWidgetATPATO")
        self.tableWidgetATPATO.setColumnCount(3)
        self.tableWidgetATPATO.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetATPATO.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetATPATO.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetATPATO.setHorizontalHeaderItem(2, item)
        self.horizontalLayout_8.addWidget(self.tableWidgetATPATO)
        self.horizontalLayout_5.addWidget(self.groupBox_3)
        self.groupBox_4 = QtWidgets.QGroupBox(self.layoutWidget2)
        self.groupBox_4.setObjectName("groupBox_4")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.groupBox = QtWidgets.QGroupBox(self.groupBox_4)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_9.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setMaximumSize(QtCore.QSize(40, 20))
        self.label_6.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_9.addWidget(self.label_6)
        self.line = QtWidgets.QFrame(self.groupBox)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_9.addWidget(self.line)
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setMaximumSize(QtCore.QSize(40, 20))
        self.label_8.setStyleSheet("alternate-background-color: rgb(255, 255, 255);\n"
"background-color: rgb(170, 170, 255);")
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_9.addWidget(self.label_8)
        self.line_2 = QtWidgets.QFrame(self.groupBox)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_9.addWidget(self.line_2)
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setMaximumSize(QtCore.QSize(48, 20))
        self.label_7.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_9.addWidget(self.label_7)
        self.line_3 = QtWidgets.QFrame(self.groupBox)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout_9.addWidget(self.line_3)
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setMaximumSize(QtCore.QSize(48, 20))
        self.label_9.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_9.addWidget(self.label_9)
        self.verticalLayout_8.addLayout(self.horizontalLayout_9)
        self.tableWidgetPlan = QtWidgets.QTableWidget(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidgetPlan.sizePolicy().hasHeightForWidth())
        self.tableWidgetPlan.setSizePolicy(sizePolicy)
        self.tableWidgetPlan.setBaseSize(QtCore.QSize(0, 0))
        self.tableWidgetPlan.setAutoScroll(True)
        self.tableWidgetPlan.setObjectName("tableWidgetPlan")
        self.tableWidgetPlan.setColumnCount(8)
        self.tableWidgetPlan.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetPlan.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetPlan.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetPlan.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetPlan.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetPlan.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetPlan.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetPlan.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetPlan.setHorizontalHeaderItem(7, item)
        self.tableWidgetPlan.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidgetPlan.horizontalHeader().setDefaultSectionSize(62)
        self.tableWidgetPlan.horizontalHeader().setMinimumSectionSize(18)
        self.tableWidgetPlan.horizontalHeader().setSortIndicatorShown(False)
        self.verticalLayout_8.addWidget(self.tableWidgetPlan)
        self.horizontalLayout_6.addWidget(self.groupBox)
        self.tableWidgetWL = QtWidgets.QTableWidget(self.groupBox_4)
        self.tableWidgetWL.setObjectName("tableWidgetWL")
        self.tableWidgetWL.setColumnCount(3)
        self.tableWidgetWL.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetWL.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetWL.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetWL.setHorizontalHeaderItem(2, item)
        self.horizontalLayout_6.addWidget(self.tableWidgetWL)
        self.horizontalLayout_5.addWidget(self.groupBox_4)
        self.widget_2 = QtWidgets.QWidget(self.splitter_4)
        self.widget_2.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_2.addWidget(self.splitter_4)
        self.stackedWidget.addWidget(self.page_4)
        self.layoutWidget3 = QtWidgets.QWidget(self.splitter)
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout_4.setContentsMargins(10, 0, 10, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.gridLayout_2.setVerticalSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lbl_hpm = QtWidgets.QLabel(self.layoutWidget3)
        self.lbl_hpm.setMaximumSize(QtCore.QSize(16777215, 20))
        self.lbl_hpm.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.lbl_hpm.setObjectName("lbl_hpm")
        self.gridLayout_2.addWidget(self.lbl_hpm, 0, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.lbl_mode = QtWidgets.QLabel(self.layoutWidget3)
        self.lbl_mode.setMaximumSize(QtCore.QSize(16777215, 20))
        self.lbl_mode.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.lbl_mode.setObjectName("lbl_mode")
        self.gridLayout_2.addWidget(self.lbl_mode, 0, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.lbl_carpm = QtWidgets.QLabel(self.layoutWidget3)
        self.lbl_carpm.setMaximumSize(QtCore.QSize(16777215, 20))
        self.lbl_carpm.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.lbl_carpm.setObjectName("lbl_carpm")
        self.gridLayout_2.addWidget(self.lbl_carpm, 0, 3, 1, 1, QtCore.Qt.AlignHCenter)
        self.lbl_dcmd = QtWidgets.QLabel(self.layoutWidget3)
        self.lbl_dcmd.setMaximumSize(QtCore.QSize(16777215, 20))
        self.lbl_dcmd.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.lbl_dcmd.setObjectName("lbl_dcmd")
        self.gridLayout_2.addWidget(self.lbl_dcmd, 0, 7, 1, 1, QtCore.Qt.AlignHCenter)
        self.lbl_trainlen = QtWidgets.QLabel(self.layoutWidget3)
        self.lbl_trainlen.setMaximumSize(QtCore.QSize(16777215, 20))
        self.lbl_trainlen.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.lbl_trainlen.setObjectName("lbl_trainlen")
        self.gridLayout_2.addWidget(self.lbl_trainlen, 0, 6, 1, 1, QtCore.Qt.AlignHCenter)
        self.lbl_stn = QtWidgets.QLabel(self.layoutWidget3)
        self.lbl_stn.setMaximumSize(QtCore.QSize(16777215, 20))
        self.lbl_stn.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.lbl_stn.setObjectName("lbl_stn")
        self.gridLayout_2.addWidget(self.lbl_stn, 0, 11, 1, 1, QtCore.Qt.AlignHCenter)
        self.lbl_lamp = QtWidgets.QLabel(self.layoutWidget3)
        self.lbl_lamp.setMaximumSize(QtCore.QSize(16777215, 20))
        self.lbl_lamp.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.lbl_lamp.setObjectName("lbl_lamp")
        self.gridLayout_2.addWidget(self.lbl_lamp, 0, 5, 1, 1, QtCore.Qt.AlignHCenter)
        self.lbl_pm = QtWidgets.QLabel(self.layoutWidget3)
        self.lbl_pm.setMaximumSize(QtCore.QSize(16777215, 20))
        self.lbl_pm.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.lbl_pm.setObjectName("lbl_pm")
        self.gridLayout_2.addWidget(self.lbl_pm, 0, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.lbl_check = QtWidgets.QLabel(self.layoutWidget3)
        self.lbl_check.setMaximumSize(QtCore.QSize(16777215, 20))
        self.lbl_check.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.lbl_check.setObjectName("lbl_check")
        self.gridLayout_2.addWidget(self.lbl_check, 0, 4, 1, 1, QtCore.Qt.AlignHCenter)
        self.lbl_doorstatus = QtWidgets.QLabel(self.layoutWidget3)
        self.lbl_doorstatus.setMaximumSize(QtCore.QSize(16777215, 20))
        self.lbl_doorstatus.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.lbl_doorstatus.setObjectName("lbl_doorstatus")
        self.gridLayout_2.addWidget(self.lbl_doorstatus, 0, 9, 1, 1, QtCore.Qt.AlignHCenter)
        self.lbl_freq = QtWidgets.QLabel(self.layoutWidget3)
        self.lbl_freq.setMaximumSize(QtCore.QSize(16777215, 20))
        self.lbl_freq.setStyleSheet("background-color: rgb(170, 170, 255);\n"
"selection-background-color: rgb(255, 170, 0);")
        self.lbl_freq.setObjectName("lbl_freq")
        self.gridLayout_2.addWidget(self.lbl_freq, 0, 10, 1, 1, QtCore.Qt.AlignHCenter)
        self.lbl_atpdcmd = QtWidgets.QLabel(self.layoutWidget3)
        self.lbl_atpdcmd.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.lbl_atpdcmd.setObjectName("lbl_atpdcmd")
        self.gridLayout_2.addWidget(self.lbl_atpdcmd, 0, 8, 1, 1, QtCore.Qt.AlignHCenter)
        self.verticalLayout_4.addLayout(self.gridLayout_2)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.gridLayout_3.setVerticalSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.CBvato = QtWidgets.QCheckBox(self.layoutWidget3)
        self.CBvato.setMaximumSize(QtCore.QSize(101, 25))
        self.CBvato.setObjectName("CBvato")
        self.gridLayout_3.addWidget(self.CBvato, 0, 0, 1, 1)
        self.CBcmdv = QtWidgets.QCheckBox(self.layoutWidget3)
        self.CBcmdv.setMaximumSize(QtCore.QSize(101, 25))
        self.CBcmdv.setObjectName("CBcmdv")
        self.gridLayout_3.addWidget(self.CBcmdv, 0, 1, 1, 1)
        self.CBatpcmdv = QtWidgets.QCheckBox(self.layoutWidget3)
        self.CBatpcmdv.setMaximumSize(QtCore.QSize(101, 25))
        self.CBatpcmdv.setObjectName("CBatpcmdv")
        self.gridLayout_3.addWidget(self.CBatpcmdv, 0, 2, 1, 1)
        self.CBlevel = QtWidgets.QCheckBox(self.layoutWidget3)
        self.CBlevel.setMaximumSize(QtCore.QSize(101, 25))
        self.CBlevel.setObjectName("CBlevel")
        self.gridLayout_3.addWidget(self.CBlevel, 0, 3, 1, 1)
        self.CBacc = QtWidgets.QCheckBox(self.layoutWidget3)
        self.CBacc.setMaximumSize(QtCore.QSize(101, 25))
        self.CBacc.setObjectName("CBacc")
        self.gridLayout_3.addWidget(self.CBacc, 0, 4, 1, 1)
        self.CBramp = QtWidgets.QCheckBox(self.layoutWidget3)
        self.CBramp.setMaximumSize(QtCore.QSize(101, 25))
        self.CBramp.setObjectName("CBramp")
        self.gridLayout_3.addWidget(self.CBramp, 0, 5, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout_3)
        self.layoutWidget4 = QtWidgets.QWidget(self.splitter_3)
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget4)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget4)
        self.label.setMinimumSize(QtCore.QSize(50, 0))
        self.label.setMaximumSize(QtCore.QSize(50, 16777215))
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_2.setMinimumSize(QtCore.QSize(90, 0))
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_3.setMaximumSize(QtCore.QSize(55, 16777215))
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.spinBox = QtWidgets.QSpinBox(self.layoutWidget4)
        self.spinBox.setMaximumSize(QtCore.QSize(70, 16777215))
        self.spinBox.setObjectName("spinBox")
        self.horizontalLayout.addWidget(self.spinBox)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tabWidget = QtWidgets.QTabWidget(self.layoutWidget4)
        self.tabWidget.setMaximumSize(QtCore.QSize(800, 16777215))
        self.tabWidget.setStyleSheet("")
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setObjectName("tabWidget")
        self.atotab = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(30)
        sizePolicy.setHeightForWidth(self.atotab.sizePolicy().hasHeightForWidth())
        self.atotab.setSizePolicy(sizePolicy)
        self.atotab.setMaximumSize(QtCore.QSize(800, 16777215))
        self.atotab.setAutoFillBackground(False)
        self.atotab.setObjectName("atotab")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.atotab)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.splitter_2 = QtWidgets.QSplitter(self.atotab)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName("splitter_2")
        self.tableWidget = QtWidgets.QTableWidget(self.splitter_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        self.tableWidget.setMaximumSize(QtCore.QSize(800, 16777215))
        self.tableWidget.setStyleSheet("background-color: rgb(224, 238, 224);")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.treeWidget = QtWidgets.QTreeWidget(self.splitter_2)
        self.treeWidget.setMaximumSize(QtCore.QSize(800, 16777215))
        self.treeWidget.setStyleSheet("background-color: rgb(230, 230, 255);")
        self.treeWidget.setObjectName("treeWidget")
        self.treeWidget.headerItem().setText(0, "1")
        self.treeWidget.header().setDefaultSectionSize(80)
        self.horizontalLayout_2.addWidget(self.splitter_2)
        self.tabWidget.addTab(self.atotab, "")
        self.fietab = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fietab.sizePolicy().hasHeightForWidth())
        self.fietab.setSizePolicy(sizePolicy)
        self.fietab.setMaximumSize(QtCore.QSize(800, 16777215))
        self.fietab.setObjectName("fietab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.fietab)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.treeView = QtWidgets.QTreeView(self.fietab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(30)
        sizePolicy.setHeightForWidth(self.treeView.sizePolicy().hasHeightForWidth())
        self.treeView.setSizePolicy(sizePolicy)
        self.treeView.setMaximumSize(QtCore.QSize(800, 16777215))
        self.treeView.setObjectName("treeView")
        self.verticalLayout_3.addWidget(self.treeView)
        self.tabWidget.addTab(self.fietab, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.progressBar = QtWidgets.QProgressBar(self.layoutWidget4)
        self.progressBar.setMinimumSize(QtCore.QSize(250, 0))
        self.progressBar.setMaximumSize(QtCore.QSize(800, 30))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout.addWidget(self.progressBar)
        self.textEdit = QtWidgets.QTextEdit(self.layoutWidget4)
        self.textEdit.setMinimumSize(QtCore.QSize(250, 0))
        self.textEdit.setMaximumSize(QtCore.QSize(800, 100))
        self.textEdit.setStyleSheet("background-color: rgb(255, 250, 205);")
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout.addWidget(self.textEdit)
        self.horizontalLayout_3.addWidget(self.splitter_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 23))
        self.menubar.setObjectName("menubar")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(self.menubar)
        self.menu_3.setObjectName("menu_3")
        self.menu_7 = QtWidgets.QMenu(self.menu_3)
        self.menu_7.setObjectName("menu_7")
        self.menu_4 = QtWidgets.QMenu(self.menubar)
        self.menu_4.setObjectName("menu_4")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_5 = QtWidgets.QMenu(self.menubar)
        self.menu_5.setObjectName("menu_5")
        self.menu_6 = QtWidgets.QMenu(self.menubar)
        self.menu_6.setObjectName("menu_6")
        self.menu_8 = QtWidgets.QMenu(self.menubar)
        self.menu_8.setObjectName("menu_8")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.fileOpen = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("IconFiles/file.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.fileOpen.setIcon(icon)
        self.fileOpen.setObjectName("fileOpen")
        self.fileClose = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("IconFiles/close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.fileClose.setIcon(icon1)
        self.fileClose.setObjectName("fileClose")
        self.fileSave = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("IconFiles/save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.fileSave.setIcon(icon2)
        self.fileSave.setObjectName("fileSave")
        self.Exit = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("IconFiles/quit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Exit.setIcon(icon3)
        self.Exit.setObjectName("Exit")
        self.actionVersion = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("IconFiles/version.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionVersion.setIcon(icon4)
        self.actionVersion.setObjectName("actionVersion")
        self.actionHelp = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("IconFiles/help.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionHelp.setIcon(icon5)
        self.actionHelp.setObjectName("actionHelp")
        self.actionTag = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("IconFiles/tag.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionTag.setIcon(icon6)
        self.actionTag.setObjectName("actionTag")
        self.actionView = QtWidgets.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("IconFiles/view.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionView.setIcon(icon7)
        self.actionView.setObjectName("actionView")
        self.actionPan = QtWidgets.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("IconFiles/pan.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPan.setIcon(icon8)
        self.actionPan.setObjectName("actionPan")
        self.actionZoom = QtWidgets.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("IconFiles/zoom.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionZoom.setIcon(icon9)
        self.actionZoom.setObjectName("actionZoom")
        self.actionConfig = QtWidgets.QAction(MainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("IconFiles/config.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionConfig.setIcon(icon10)
        self.actionConfig.setObjectName("actionConfig")
        self.actionFwd = QtWidgets.QAction(MainWindow)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("IconFiles/forward.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFwd.setIcon(icon11)
        self.actionFwd.setObjectName("actionFwd")
        self.actionBck = QtWidgets.QAction(MainWindow)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap("IconFiles/back.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionBck.setIcon(icon12)
        self.actionBck.setObjectName("actionBck")
        self.actionEdit = QtWidgets.QAction(MainWindow)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap("IconFiles/edit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionEdit.setIcon(icon13)
        self.actionEdit.setObjectName("actionEdit")
        self.actionReset = QtWidgets.QAction(MainWindow)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap("IconFiles/reset.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionReset.setIcon(icon14)
        self.actionReset.setObjectName("actionReset")
        self.actionHome = QtWidgets.QAction(MainWindow)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap("IconFiles/home.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionHome.setIcon(icon15)
        self.actionHome.setObjectName("actionHome")
        self.actionPrint = QtWidgets.QAction(MainWindow)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap("IconFiles/print.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon16.addPixmap(QtGui.QPixmap("../../.designer/backup/IconFiles/print.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionPrint.setIcon(icon16)
        self.actionPrint.setObjectName("actionPrint")
        self.actionVS = QtWidgets.QAction(MainWindow)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap("IconFiles/vscurve.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionVS.setIcon(icon17)
        self.actionVS.setObjectName("actionVS")
        self.actionCS = QtWidgets.QAction(MainWindow)
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap("IconFiles/cyclecurve.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCS.setIcon(icon18)
        self.actionCS.setObjectName("actionCS")
        self.actionSerSet = QtWidgets.QAction(MainWindow)
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap("IconFiles/serset.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSerSet.setIcon(icon19)
        self.actionSerSet.setObjectName("actionSerSet")
        self.actionoffline = QtWidgets.QAction(MainWindow)
        icon20 = QtGui.QIcon()
        icon20.addPixmap(QtGui.QPixmap("IconFiles/offline.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionoffline.setIcon(icon20)
        self.actionoffline.setObjectName("actionoffline")
        self.actionRealtime = QtWidgets.QAction(MainWindow)
        icon21 = QtGui.QIcon()
        icon21.addPixmap(QtGui.QPixmap("IconFiles/realtime.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRealtime.setIcon(icon21)
        self.actionRealtime.setObjectName("actionRealtime")
        self.actionBTM = QtWidgets.QAction(MainWindow)
        self.actionBTM.setCheckable(True)
        self.actionBTM.setObjectName("actionBTM")
        self.actionJD = QtWidgets.QAction(MainWindow)
        self.actionJD.setCheckable(True)
        self.actionJD.setObjectName("actionJD")
        self.actionWL = QtWidgets.QAction(MainWindow)
        self.actionWL.setCheckable(True)
        self.actionWL.setObjectName("actionWL")
        self.actionMVB = QtWidgets.QAction(MainWindow)
        self.actionMVB.setObjectName("actionMVB")
        self.actionUTC = QtWidgets.QAction(MainWindow)
        self.actionUTC.setObjectName("actionUTC")
        self.actionMVBParser = QtWidgets.QAction(MainWindow)
        self.actionMVBParser.setObjectName("actionMVBParser")
        self.menu_2.addAction(self.actionoffline)
        self.menu_2.addAction(self.actionRealtime)
        self.menu_7.addAction(self.actionReset)
        self.menu_7.addAction(self.actionEdit)
        self.menu_7.addAction(self.actionConfig)
        self.menu_7.addAction(self.actionZoom)
        self.menu_7.addAction(self.actionPan)
        self.menu_7.addAction(self.actionFwd)
        self.menu_7.addAction(self.actionBck)
        self.menu_7.addAction(self.actionHome)
        self.menu_3.addAction(self.menu_7.menuAction())
        self.menu_3.addAction(self.actionSerSet)
        self.menu_3.addAction(self.actionMVB)
        self.menu_4.addAction(self.actionHelp)
        self.menu_4.addAction(self.actionVersion)
        self.menu.addAction(self.fileOpen)
        self.menu.addAction(self.fileClose)
        self.menu.addAction(self.fileSave)
        self.menu.addAction(self.Exit)
        self.menu_5.addAction(self.actionVS)
        self.menu_5.addAction(self.actionCS)
        self.menu_6.addAction(self.actionBTM)
        self.menu_6.addAction(self.actionJD)
        self.menu_6.addAction(self.actionWL)
        self.menu_8.addAction(self.actionUTC)
        self.menu_8.addAction(self.actionMVBParser)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu_5.menuAction())
        self.menubar.addAction(self.menu_6.menuAction())
        self.menubar.addAction(self.menu_8.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())
        self.menubar.addAction(self.menu_4.menuAction())
        self.toolBar.addAction(self.actionTag)
        self.toolBar.addAction(self.actionView)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionHome)
        self.toolBar.addAction(self.actionBck)
        self.toolBar.addAction(self.actionFwd)
        self.toolBar.addAction(self.actionEdit)
        self.toolBar.addAction(self.actionConfig)
        self.toolBar.addAction(self.actionZoom)
        self.toolBar.addAction(self.actionPan)
        self.toolBar.addAction(self.actionReset)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionPrint)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(1)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_4.setText(_translate("MainWindow", "保存路径"))
        self.btn_SavePath.setText(_translate("MainWindow", "..."))
        self.btn_PortLink.setText(_translate("MainWindow", "连接"))
        self.gp_ato2tcms.setTitle(_translate("MainWindow", "ATO2TCMS"))
        self.gp_ato2tcms_ctrl.setTitle(_translate("MainWindow", "Ctrl_Info"))
        self.lbl_ctrl_hrt.setText(_translate("MainWindow", "ATO心跳"))
        self.lbl_ctrl_costspeed.setText(_translate("MainWindow", "恒速命令"))
        self.lbl_ctrl_rdoor.setText(_translate("MainWindow", "开右门"))
        self.lbl_ctrl_trac.setText(_translate("MainWindow", "牵引量"))
        self.lbl_ctrl_brake.setText(_translate("MainWindow", "制动量"))
        self.lbl_ctrl_tbstat.setText(_translate("MainWindow", "命令状态"))
        self.lbl_ctrl_keepbrake.setText(_translate("MainWindow", "保持制动"))
        self.lbl_ctrl_ldoor.setText(_translate("MainWindow", "开左门"))
        self.lbl_ctrl_atovalid.setText(_translate("MainWindow", "ATO有效"))
        self.lbl_startlamp.setText(_translate("MainWindow", "启动灯"))
        self.lbl_ctrl_aimspeed.setText(_translate("MainWindow", "恒速目标"))
        self.gp_ato2tcms_status.setTitle(_translate("MainWindow", "Status_Info"))
        self.lbl_stat_tunnelin.setText(_translate("MainWindow", "隧道入口"))
        self.lbl_stat_hrt.setText(_translate("MainWindow", "ATO心跳"))
        self.lbl_stat_atospeed.setText(_translate("MainWindow", "ATO速度"))
        self.lbl_stat_error.setText(_translate("MainWindow", "ATO故障"))
        self.lbl_stat_stonemile.setText(_translate("MainWindow", "公里标"))
        self.lbl_stat_tunnellen.setText(_translate("MainWindow", "隧道长度"))
        self.groupBox_2.setTitle(_translate("MainWindow", "TCMS2ATO"))
        self.lbl_tcms_pm.setText(_translate("MainWindow", "动车组允许"))
        self.lbl_tcms_breakstat.setText(_translate("MainWindow", "主断状态"))
        self.lbl_tcms_tbstat.setText(_translate("MainWindow", "牵控状态反馈"))
        self.lbl_tcms_nunits.setText(_translate("MainWindow", "编组信息"))
        self.lbl_tcms_am.setText(_translate("MainWindow", "门控AM"))
        self.lbl_tcms_hrt.setText(_translate("MainWindow", "TCMS心跳"))
        self.lbl_tcms_costspeedfbk.setText(_translate("MainWindow", "恒速反馈"))
        self.lbl_tcms_bstat.setText(_translate("MainWindow", "制动反馈"))
        self.lbl_tcms_tractfbk.setText(_translate("MainWindow", "牵引反馈"))
        self.lbl_tcms_mm.setText(_translate("MainWindow", "门控MM"))
        self.lbl_tcms_doorstat.setText(_translate("MainWindow", "车门状态"))
        self.lbl_tcms_keepbfbk.setText(_translate("MainWindow", "保持制动反馈"))
        self.lbl_tcms_dh.setText(_translate("MainWindow", "打滑发生"))
        self.lbl_tcms_mandoorpm.setText(_translate("MainWindow", "人工门允许"))
        self.lbl_tcms_atpdoorpm.setText(_translate("MainWindow", "ATP门允许"))
        self.lbl_tcms_weight.setText(_translate("MainWindow", "车重"))
        self.lbl_tcms_kz.setText(_translate("MainWindow", "空转发生"))
        self.lbl_tcms_rdoorfbk.setText(_translate("MainWindow", "开右反馈"))
        self.lbl_tcms_ldoorfbk.setText(_translate("MainWindow", "开左反馈"))
        self.lbl_tcms_atovalid_fbk.setText(_translate("MainWindow", "ATO有效反馈"))
        self.lbl_tcms_startlampfbk.setText(_translate("MainWindow", "启动灯反馈"))
        self.groupBox_3.setTitle(_translate("MainWindow", "ATO-ATP"))
        self.groupBox_6.setTitle(_translate("MainWindow", "关键信息"))
        item = self.tableWidgetATPATO.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "时间"))
        item = self.tableWidgetATPATO.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "方向"))
        item = self.tableWidgetATPATO.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "数据包"))
        self.groupBox_4.setTitle(_translate("MainWindow", "ATO-TSRS"))
        self.groupBox.setTitle(_translate("MainWindow", "PLAN_INFO"))
        self.label_5.setText(_translate("MainWindow", "计划判断:"))
        self.label_6.setText(_translate("MainWindow", "有效性"))
        self.label_8.setText(_translate("MainWindow", "合法性"))
        self.label_7.setText(_translate("MainWindow", "是否超时"))
        self.label_9.setText(_translate("MainWindow", "是否终点"))
        item = self.tableWidgetPlan.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "段序号"))
        item = self.tableWidgetPlan.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "发车股道"))
        item = self.tableWidgetPlan.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "发车时间"))
        item = self.tableWidgetPlan.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "接车股道"))
        item = self.tableWidgetPlan.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "接车时间"))
        item = self.tableWidgetPlan.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "地面时刻"))
        item = self.tableWidgetPlan.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "到发"))
        item = self.tableWidgetPlan.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "办客"))
        item = self.tableWidgetWL.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "时间"))
        item = self.tableWidgetWL.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "方向"))
        item = self.tableWidgetWL.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "数据包"))
        self.lbl_hpm.setText(_translate("MainWindow", "硬允许"))
        self.lbl_mode.setText(_translate("MainWindow", "ATO模式"))
        self.lbl_carpm.setText(_translate("MainWindow", "车辆允许"))
        self.lbl_dcmd.setText(_translate("MainWindow", "主断状态"))
        self.lbl_trainlen.setText(_translate("MainWindow", "列车车长"))
        self.lbl_stn.setText(_translate("MainWindow", "站台标志"))
        self.lbl_lamp.setText(_translate("MainWindow", "发车灯"))
        self.lbl_pm.setText(_translate("MainWindow", "软允许"))
        self.lbl_check.setText(_translate("MainWindow", "自检状态"))
        self.lbl_doorstatus.setText(_translate("MainWindow", "门状态"))
        self.lbl_freq.setText(_translate("MainWindow", "轨道低频"))
        self.lbl_atpdcmd.setText(_translate("MainWindow", "分相区"))
        self.CBvato.setText(_translate("MainWindow", "S-Vato"))
        self.CBcmdv.setText(_translate("MainWindow", "S-Vatocmdv"))
        self.CBatpcmdv.setText(_translate("MainWindow", "S-Vatpcmdv"))
        self.CBlevel.setText(_translate("MainWindow", "S-Level"))
        self.CBacc.setText(_translate("MainWindow", "S-Acc"))
        self.CBramp.setText(_translate("MainWindow", "S-Ramp"))
        self.label.setText(_translate("MainWindow", "时间"))
        self.label_2.setText(_translate("MainWindow", "Y:M:D:H:M:S"))
        self.label_3.setText(_translate("MainWindow", "周期"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.atotab), _translate("MainWindow", "ATO控制信息"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.fietab), _translate("MainWindow", "文件选择框"))
        self.menu_2.setTitle(_translate("MainWindow", "模式"))
        self.menu_3.setTitle(_translate("MainWindow", "设置"))
        self.menu_7.setTitle(_translate("MainWindow", "绘图设置"))
        self.menu_4.setTitle(_translate("MainWindow", "关于"))
        self.menu.setTitle(_translate("MainWindow", "文件"))
        self.menu_5.setTitle(_translate("MainWindow", "曲线"))
        self.menu_6.setTitle(_translate("MainWindow", "事件"))
        self.menu_8.setTitle(_translate("MainWindow", "工具"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.fileOpen.setText(_translate("MainWindow", "打开记录"))
        self.fileClose.setText(_translate("MainWindow", "关闭记录"))
        self.fileSave.setText(_translate("MainWindow", "保存曲线"))
        self.Exit.setText(_translate("MainWindow", "退出"))
        self.actionVersion.setText(_translate("MainWindow", "版本信息"))
        self.actionHelp.setText(_translate("MainWindow", "帮助"))
        self.actionTag.setText(_translate("MainWindow", "标注模式"))
        self.actionView.setText(_translate("MainWindow", "浏览模式"))
        self.actionPan.setText(_translate("MainWindow", "图形拖放"))
        self.actionPan.setToolTip(_translate("MainWindow", "图形拖放，左键拖动，右键坐标轴缩放"))
        self.actionZoom.setText(_translate("MainWindow", "图形缩放"))
        self.actionZoom.setToolTip(_translate("MainWindow", "图形缩放，鼠标拖拽放大"))
        self.actionConfig.setText(_translate("MainWindow", "参数配置"))
        self.actionFwd.setText(_translate("MainWindow", "前进"))
        self.actionBck.setText(_translate("MainWindow", "后退"))
        self.actionEdit.setText(_translate("MainWindow", "图形编辑"))
        self.actionReset.setText(_translate("MainWindow", "重置图形"))
        self.actionReset.setToolTip(_translate("MainWindow", "重新绘制曲线"))
        self.actionHome.setText(_translate("MainWindow", "原始显示"))
        self.actionHome.setToolTip(_translate("MainWindow", "显示初始坐标轴"))
        self.actionPrint.setText(_translate("MainWindow", "打印周期"))
        self.actionPrint.setToolTip(_translate("MainWindow", "打印当前周期记录"))
        self.actionVS.setText(_translate("MainWindow", "位置速度曲线"))
        self.actionCS.setText(_translate("MainWindow", "周期速度曲线"))
        self.actionSerSet.setText(_translate("MainWindow", "串口设置"))
        self.actionSerSet.setToolTip(_translate("MainWindow", "用于窗口和文件保存路径设置"))
        self.actionoffline.setText(_translate("MainWindow", "离线数据分析"))
        self.actionoffline.setToolTip(_translate("MainWindow", "选择离线ATO记录分析显示"))
        self.actionRealtime.setText(_translate("MainWindow", "实时数据分析"))
        self.actionRealtime.setToolTip(_translate("MainWindow", "实时分析ATO串口记录"))
        self.actionBTM.setText(_translate("MainWindow", "ATP应答器数据"))
        self.actionBTM.setToolTip(_translate("MainWindow", "ATO收到的ATP发送的应答器数据"))
        self.actionJD.setText(_translate("MainWindow", "JD停车点更新"))
        self.actionWL.setText(_translate("MainWindow", "无线呼叫命令"))
        self.actionWL.setToolTip(_translate("MainWindow", "来自应答器或司机手输的无线呼叫命令"))
        self.actionMVB.setText(_translate("MainWindow", "MVB端口设置"))
        self.actionUTC.setText(_translate("MainWindow", "UTC时间转换器"))
        self.actionMVBParser.setText(_translate("MainWindow", "MVB解析器"))

import IconFiles_rc
